name: nfresh
description: nfresh

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

  page_indicator: ^0.2.0
  dots_indicator: ^0.0.5
  share:
    git:
      url: https://github.com/d-silveira/flutter-share.git
  dotted_border: ^0.1.1
  pin_entry_text_field: ^0.1.3
  pin_view: ^1.0.1
  shared_preferences: ^0.5.3
  http: ^0.12.0+2
  rxdart: ^0.18.0
  sqflite: ^1.1.5
  path_provider: ^1.1.0
  toast: ^0.1.3
  progress_dialog: ^1.1.0+1
  #onesignal: ^1.1.0
  firebase_messaging: ^5.1.2
  firebase_core: ^0.4.0+6
  flutter_staggered_grid_view: ^0.3.0
  #flutter_appavailability: ^0.0.21
  connectivity: ^0.4.3+6
  flutter_web_view: ^0.0.6
  flutter_webview_plugin: ^0.3.5
  grouped_buttons: ^1.0.4
  #flutter_email_sender: ^2.0.3
  url_launcher: ^3.0.1
  pull_to_refresh: ^1.5.4
  cached_network_image: ^1.1.1
  page_transition: ^1.1.4


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - logo.png
    - ribbon.png
    - settings.png
    - veg.png
    - fruit.png
    - pea.png
    - noti.png
    - delete.png
    - share.png
    - cart.png
    - fav_filled.png
    - premium.png
    - sort.png
    - selected_list.png
    - unselected_list.png
    - selected_grid.png
    - unselected_grid.png
    - cvegg.png
    - search.png
    - fav.png
    - sigbg.jpg
    - dummy.jpg
    - bg.jpg
    - cate.png
    - contactus.png
    - help.png
    - logout.png
    - mywallet.png
    - offer.png
    - orderhistory.png
    - otp.png
    - donepromo.png
    - setting.png
    - homel.png
    - minus.png
    - plus.png
    - refer.png
    - fb.png
    - mail.png
    - message.png
    - wa.png
    - noti_admin.png
    - noti_order.png
    - noti_wallet.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
#   fonts:
#     - family: Schyler
#       fonts:
#         - asset: fonts/sansprobold.ttf

  #         style: italic
  #   - family: Trajan Pro
  fonts:
    - family: Bold
      fonts:
        - asset: fonts/sansprobold.ttf
        - asset: fonts/sansregular.ttf
        - asset: fonts/sansitalic.ttf
          weight: 400

  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
